dnsproxy: Fix uninitialized false positive in dnsproxy
gcc reports with:

 git/src/dnsproxy.c: In function 'update_domain':
 git/src/dnsproxy.c:2735:4: error: 'dom' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  2735 |    g_free(dom);
       |    ^~~~~~~~~~~

(cherry picked from commit bd16cb1a50a7f081c11f392626e18b86d3ec2b47)