session: Fix state initializiation
gcc complains about using the wrong enum type:

src/session.c:1808:38: error: implicit conversion from ‘enum connman_session_state’ to ‘enum connman_service_state’ [-Werror=enum-conversion]
 1808 |   enum connman_service_state state = CONNMAN_SESSION_STATE_DISCONNECTED;
x

(cherry picked from commit 8f21157ead3feea65898b891d3b4b98dbfae2544)